import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    nav_home: 'Home',
    nav_about: 'About',
    nav_login: 'Login',
    hero_title: 'Web Cyberattack Detection Platform',
    hero_subtitle: 'Advanced AI-powered intelligence specialized in detecting web-based cyberattacks — SQL Injection, Cross-Site Scripting (XSS), phishing URLs, WAF bypass attempts, malicious payloads, and web application exploits — in real time.',
    hero_cta: 'Access Platform',
    hero_cta_learn: 'Learn More',
    features_title: 'Platform Capabilities',
    features_sub: 'A complete web threat intelligence suite powered by Machine Learning, NLP, and WAF log analysis — purpose-built to detect and analyze web-based attacks.',
    about_title: 'About CyberGuard',
    about_body: 'CyberGuard is an advanced web cyberattack detection platform built for security analysts and academic research. It combines a Random Forest Machine Learning engine, Natural Language Processing, and Web Application Firewall (WAF) log analysis to detect and classify web-based threats — including SQL Injection (SQLi), Cross-Site Scripting (XSS), phishing URLs, WAF bypass attempts, malicious payloads, Brute Force attacks, and Zero-Day web exploits. The platform also performs GeoIP threat tracing, ASN/Proxy detection, and generates SHA-256 cryptographically signed incident reports for forensic investigation.',
    footer_platform: 'Platform',
    footer_features: 'Features',
    footer_resources: 'Resources',
    footer_legal: 'Legal',
    footer_desc: 'Intelligent web cyberattack detection platform — specialized in SQLi, XSS, phishing, and web exploit analysis — powered by Machine Learning.',
    footer_copy: '© 2026 CyberGuard. All rights reserved.',
    login_title: 'Sign in to CyberGuard',
    login_sub: 'Enter your credentials to access the SOC platform',
    login_email: 'Email address',
    login_password: 'Password',
    login_btn: 'Sign In',
    login_authenticating: 'Authenticating...',
    login_sub_creds: 'Sign in with your credentials to access the platform',
    login_back_home: '← Back to Home',
    login_no_account: "Don't have an account?",
    login_create: 'Create Account',
    login_forgot: 'Forgot password?',
    login_direct: 'Or access platform directly',
    login_invalid: 'Incorrect email or password',
    login_failed: 'Login failed',
    login_err_creds: 'Incorrect email or password. Please verify your credentials.',
    login_err_disabled: 'This account has been deactivated. Please contact an administrator.',
    login_err_network: 'Unable to reach the server. Please verify your connection or backend status.',
    login_err_server: 'Internal server error (500). Please check backend logs or try again later.',
    demo_soc_label: 'SOC Investigator',
    demo_soc_desc: 'Incident triage & evidence vault',
    demo_admin_label: 'Administrator',
    demo_admin_desc: 'Full system & user role management',
    demo_user_label: 'Standard User',
    demo_user_desc: 'AI URL & message threat scanner',
    register_title: 'Create your account',
    register_sub: 'Join the CyberGuard cybersecurity platform',
    register_name: 'Full Name',
    register_email: 'Email address',
    register_password: 'Password',
    register_confirm: 'Confirm Password',
    register_role: 'Role',
    register_role_analyst: 'Security Analyst',
    register_role_admin: 'Administrator',
    register_terms: 'I agree to the Terms of Service and Privacy Policy',
    register_btn: 'Create Account',
    register_have_account: 'Already have an account?',
    register_signin: 'Sign In',
    carousel_prev: 'Previous',
    carousel_next: 'Next',
    footer_soc_dash: 'SOC Dashboard',
    footer_url_scan: 'URL Scanner',
    footer_sms_email: 'SMS & Email Analysis',
    footer_waf: 'Web Attack Monitor',
    footer_incidents: 'Incidents & Evidence',
    footer_investigator: 'Investigator Portal',
    footer_ai: 'AI Security Advisor',
    footer_geoip: 'GeoIP Threat Tracing',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_research: 'Security Research',
    footer_contact: 'Contact Us',
    footer_status: 'All systems operational',
  },
  fr: {
    nav_home: 'Accueil',
    nav_about: 'À propos',
    nav_login: 'Connexion',
    hero_title: 'Plateforme de Détection des Cyberattaques Web',
    hero_subtitle: "Intelligence avancée alimentée par l'IA, spécialisée dans la détection des cyberattaques web — Injection SQL, Cross-Site Scripting (XSS), URLs de phishing, contournements de WAF, charges utiles malveillantes et exploits d'applications web — en temps réel.",
    hero_cta: 'Accéder à la plateforme',
    hero_cta_learn: 'En savoir plus',
    features_title: 'Capacités de la Plateforme',
    features_sub: 'Une suite complète de renseignements sur les menaces web, alimentée par le Machine Learning, le NLP et l\'analyse de journaux WAF — conçue spécifiquement pour détecter et analyser les attaques web.',
    about_title: 'À propos de CyberGuard',
    about_body: "CyberGuard est une plateforme avancée de détection des cyberattaques web, conçue pour les analystes en sécurité et la recherche académique. Elle combine un moteur de Machine Learning Random Forest, le traitement du langage naturel (NLP) et l'analyse des journaux de Pare-feu Applicatif Web (WAF) pour détecter et classifier les menaces web — notamment l'Injection SQL (SQLi), le Cross-Site Scripting (XSS), les URLs de phishing, les tentatives de contournement de WAF, les charges utiles malveillantes, les attaques par force brute et les exploits web zero-day. La plateforme effectue également un traçage de localisation des menaces par GeoIP, une détection ASN/Proxy, et génère des rapports d'incidents signés cryptographiquement par SHA-256 pour les enquêtes forensiques.",
    footer_platform: 'Plateforme',
    footer_features: 'Fonctionnalités',
    footer_resources: 'Ressources',
    footer_legal: 'Légal',
    footer_desc: 'Plateforme intelligente de détection des cyberattaques web — spécialisée dans SQLi, XSS, phishing et l\'analyse des exploits web — alimentée par le Machine Learning.',
    footer_copy: '© 2026 CyberGuard. Tous droits réservés.',
    login_title: 'Connectez-vous à CyberGuard',
    login_sub: 'Entrez vos identifiants pour accéder à la plateforme SOC',
    login_email: 'Adresse e-mail',
    login_password: 'Mot de passe',
    login_btn: 'Se connecter',
    login_authenticating: 'Authentification en cours...',
    login_sub_creds: 'Saisissez vos identifiants pour accéder à la plateforme',
    login_back_home: '← Retour à l\'accueil',
    login_no_account: 'Pas encore de compte ?',
    login_create: 'Créer un compte',
    login_forgot: 'Mot de passe oublié ?',
    login_direct: 'Ou accéder directement à la plateforme',
    login_invalid: 'Email ou mot de passe incorrect',
    login_failed: 'Échec de la connexion',
    login_err_creds: 'Adresse e-mail ou mot de passe incorrect. Veuillez vérifier vos identifiants.',
    login_err_disabled: 'Ce compte est désactivé. Veuillez contacter un administrateur.',
    login_err_network: 'Impossible de joindre le serveur. Assurez-vous que le backend est en cours d\'exécution.',
    login_err_server: 'Erreur interne du serveur (500). Veuillez consulter les journaux du backend.',
    demo_soc_label: 'Enquêteur SOC',
    demo_soc_desc: 'Gestion des incidents & intégrité SHA-256',
    demo_admin_label: 'Administrateur',
    demo_admin_desc: 'Gestion complète des rôles & annuaire',
    demo_user_label: 'Utilisateur Standard',
    demo_user_desc: 'Scanner de menaces IA & signalement',
    register_title: 'Créez votre compte',
    register_sub: 'Rejoignez la plateforme de cybersécurité CyberGuard',
    register_name: 'Nom complet',
    register_email: 'Adresse e-mail',
    register_password: 'Mot de passe',
    register_confirm: 'Confirmer le mot de passe',
    register_role: 'Rôle',
    register_role_analyst: 'Analyste en sécurité',
    register_role_admin: 'Administrateur',
    register_terms: "J'accepte les Conditions d'utilisation et la Politique de confidentialité",
    register_btn: 'Créer un compte',
    register_have_account: 'Déjà un compte ?',
    register_signin: 'Se connecter',
    carousel_prev: 'Précédent',
    carousel_next: 'Suivant',
    footer_soc_dash: 'Tableau de bord SOC',
    footer_url_scan: "Scanner d'URL",
    footer_sms_email: 'Analyse SMS & Email',
    footer_waf: "Moniteur d'attaques web",
    footer_incidents: 'Incidents & Preuves',
    footer_investigator: 'Portail investigateur',
    footer_ai: 'Conseiller IA sécurité',
    footer_geoip: 'Traçage GeoIP',
    footer_privacy: 'Politique de confidentialité',
    footer_terms: "Conditions d'utilisation",
    footer_research: 'Recherche en sécurité',
    footer_contact: 'Nous contacter',
    footer_status: 'Tous les systèmes opérationnels',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('phishguard-lang') || 'en');
  const t = (key) => translations[lang][key] || key;
  const toggle = () => {
    const next = lang === 'en' ? 'fr' : 'en';
    setLang(next);
    localStorage.setItem('phishguard-lang', next);
  };
  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
