import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    nav_home: 'Home',
    nav_about: 'About',
    nav_login: 'Login',
    hero_title: 'Cyber Attack Detection Platform',
    hero_subtitle: 'Advanced AI-powered cybersecurity intelligence that detects phishing, malicious URLs, SQL injection, XSS, ransomware, social engineering, and more — in real time.',
    hero_cta: 'Access Platform',
    hero_cta_learn: 'Learn More',
    features_title: 'Platform Capabilities',
    features_sub: 'A complete cyber threat intelligence suite powered by Machine Learning and NLP.',
    about_title: 'About CyberGuard',
    about_body: 'CyberGuard is an advanced cyber attack detection platform built for security analysts and academic research. It combines a Random Forest Machine Learning engine, Natural Language Processing, and web application firewall log analysis to detect a wide spectrum of cyber threats — from URL phishing and SMS social engineering to SQL Injection, Cross-Site Scripting, Ransomware droppers, Brute Force attacks, and Zero-Day RCE exploits. The platform also performs GeoIP threat location tracing, ASN/Proxy detection, and generates SHA-256 cryptographically signed incident reports for forensic investigation.',
    footer_platform: 'Platform',
    footer_features: 'Features',
    footer_resources: 'Resources',
    footer_legal: 'Legal',
    footer_desc: 'Intelligent cyber threat and phishing intelligence platform powered by Machine Learning.',
    footer_copy: '© 2026 CyberGuard. All rights reserved.',
    login_title: 'Sign in to CyberGuard',
    login_sub: 'Enter your credentials to access the SOC platform',
    login_email: 'Email address',
    login_password: 'Password',
    login_btn: 'Sign In',
    login_authenticating: 'Authenticating...',
    login_sub_creds: 'Sign in with your credentials to access the platform',
    login_back_home: '← Back to Home',
    login_no_account: "Don't have an account?",
    login_create: 'Create Account',
    login_forgot: 'Forgot password?',
    login_direct: 'Or access platform directly',
    login_invalid: 'Invalid credentials',
    login_failed: 'Login failed',
    demo_soc_label: 'SOC Investigator',
    demo_soc_desc: 'Incident triage & evidence vault',
    demo_admin_label: 'Administrator',
    demo_admin_desc: 'Full system & user role management',
    demo_user_label: 'Standard User',
    demo_user_desc: 'AI URL & message threat scanner',
    register_title: 'Create your account',
    register_sub: 'Join the CyberGuard cybersecurity platform',
    register_name: 'Full Name',
    register_email: 'Email address',
    register_password: 'Password',
    register_confirm: 'Confirm Password',
    register_role: 'Role',
    register_role_analyst: 'Security Analyst',
    register_role_admin: 'Administrator',
    register_terms: 'I agree to the Terms of Service and Privacy Policy',
    register_btn: 'Create Account',
    register_have_account: 'Already have an account?',
    register_signin: 'Sign In',
    carousel_prev: 'Previous',
    carousel_next: 'Next',
    footer_soc_dash: 'SOC Dashboard',
    footer_url_scan: 'URL Scanner',
    footer_sms_email: 'SMS & Email Analysis',
    footer_waf: 'Web Attack Monitor',
    footer_incidents: 'Incidents & Evidence',
    footer_investigator: 'Investigator Portal',
    footer_ai: 'AI Security Advisor',
    footer_geoip: 'GeoIP Threat Tracing',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_research: 'Security Research',
    footer_contact: 'Contact Us',
    footer_status: 'All systems operational',
  },
  fr: {
    nav_home: 'Accueil',
    nav_about: 'À propos',
    nav_login: 'Connexion',
    hero_title: 'Plateforme de Détection des Cyberattaques',
    hero_subtitle: "Intelligence de cybersécurité avancée alimentée par l'IA qui détecte le phishing, les URL malveillantes, l'injection SQL, les XSS, les ransomwares et bien plus encore — en temps réel.",
    hero_cta: 'Accéder à la plateforme',
    hero_cta_learn: 'En savoir plus',
    features_title: 'Capacités de la Plateforme',
    features_sub: 'Une suite complète de renseignements sur les cybermenaces alimentée par le Machine Learning et le NLP.',
    about_title: 'À propos de CyberGuard',
    about_body: "CyberGuard est une plateforme avancée de détection des cyberattaques conçue pour les analystes en sécurité et la recherche académique. Elle combine un moteur de Machine Learning Random Forest, le traitement du langage naturel et l'analyse des journaux de pare-feu applicatif pour détecter un large spectre de cybermenaces — du phishing d'URL et de l'ingénierie sociale par SMS à l'injection SQL, les XSS, les ransomwares, les attaques par force brute et les exploits RCE zero-day. La plateforme effectue également un traçage de localisation des menaces par GeoIP, une détection ASN/Proxy, et génère des rapports d'incidents signés cryptographiquement par SHA-256 pour les enquêtes forensiques.",
    footer_platform: 'Plateforme',
    footer_features: 'Fonctionnalités',
    footer_resources: 'Ressources',
    footer_legal: 'Légal',
    footer_desc: 'Plateforme intelligente de renseignements sur les menaces cybernétiques et le phishing, alimentée par le Machine Learning.',
    footer_copy: '© 2026 CyberGuard. Tous droits réservés.',
    login_title: 'Connectez-vous à CyberGuard',
    login_sub: 'Entrez vos identifiants pour accéder à la plateforme SOC',
    login_email: 'Adresse e-mail',
    login_password: 'Mot de passe',
    login_btn: 'Se connecter',
    login_authenticating: 'Authentification en cours...',
    login_sub_creds: 'Saisissez vos identifiants pour accéder à la plateforme',
    login_back_home: '← Retour à l\'accueil',
    login_no_account: 'Pas encore de compte ?',
    login_create: 'Créer un compte',
    login_forgot: 'Mot de passe oublié ?',
    login_direct: 'Ou accéder directement à la plateforme',
    login_invalid: 'Email ou mot de passe incorrect',
    login_failed: 'Échec de la connexion',
    demo_soc_label: 'Enquêteur SOC',
    demo_soc_desc: 'Gestion des incidents & intégrité SHA-256',
    demo_admin_label: 'Administrateur',
    demo_admin_desc: 'Gestion complète des rôles & annuaire',
    demo_user_label: 'Utilisateur Standard',
    demo_user_desc: 'Scanner de menaces IA & signalement',
    register_title: 'Créez votre compte',
    register_sub: 'Rejoignez la plateforme de cybersécurité CyberGuard',
    register_name: 'Nom complet',
    register_email: 'Adresse e-mail',
    register_password: 'Mot de passe',
    register_confirm: 'Confirmer le mot de passe',
    register_role: 'Rôle',
    register_role_analyst: 'Analyste en sécurité',
    register_role_admin: 'Administrateur',
    register_terms: "J'accepte les Conditions d'utilisation et la Politique de confidentialité",
    register_btn: 'Créer un compte',
    register_have_account: 'Déjà un compte ?',
    register_signin: 'Se connecter',
    carousel_prev: 'Précédent',
    carousel_next: 'Suivant',
    footer_soc_dash: 'Tableau de bord SOC',
    footer_url_scan: "Scanner d'URL",
    footer_sms_email: 'Analyse SMS & Email',
    footer_waf: "Moniteur d'attaques web",
    footer_incidents: 'Incidents & Preuves',
    footer_investigator: 'Portail investigateur',
    footer_ai: 'Conseiller IA sécurité',
    footer_geoip: 'Traçage GeoIP',
    footer_privacy: 'Politique de confidentialité',
    footer_terms: "Conditions d'utilisation",
    footer_research: 'Recherche en sécurité',
    footer_contact: 'Nous contacter',
    footer_status: 'Tous les systèmes opérationnels',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('phishguard-lang') || 'en');
  const t = (key) => translations[lang][key] || key;
  const toggle = () => {
    const next = lang === 'en' ? 'fr' : 'en';
    setLang(next);
    localStorage.setItem('phishguard-lang', next);
  };
  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
